apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app3
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-getting-started
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: git@github.com:hidekazuna/tap-getting-started.git
      ref:
        branch: main
